Repository Unithraclya/sitecreators.github.io, pull requests merged in 2020-09, with the labels that each got.

#6 footer styling done
  css/base.css
  img/sprites.svg
  index.html
Labels: component

#8 Main intro section
  css/home.css
  img/workplace.jpg
  index.html
Labels: component

#9 responsiv portfolio
  css/base.css
  css/portfolio.css
  images/layout1.png
  images/layout2.png
  images/layout3.png
  images/layout4.png
  images/layout5.png
  images/layout6.png
  images/layout7.png
  images/layout8.png
  portfolio.html
Labels: component, help wanted

#16 Småfix
  css/portfolio.css
Labels: enhancement

#17 Updated about section + footer fix
  css/base.css
  css/home.css
  index.html
Labels: enhancement

#18 Reviews v1
  css/home.css
  index.html
Labels: component
